### ISSUE TITLE
Not working on Debian

### ISSUE THREAD

**Issue by onenerdyguy** [AndrewX192/lenovo-sa120-fanspeed-utility#12]
Hooked one up to a proxmox box. All drives pop right in, but the script continually doesn't find the enclosure. these fans are driving me nuts.

**Comment by mbilker** [comment]
I notice that this script only scans `/dev/sg*` and `/dev/ses*`. While running Arch Linux (Linux 4.10 kernel) on my IBM X3850 M2 with an LSI 9200-8e, there were no `/dev/sg*` or `/dev/ses*` device nodes created. I did find the controller under `/dev/bsg/*` and changed the script to control my Lenovo SA120.

**Comment by d10n** [comment]
Addressed on my branch in #11

**Comment by onenerdyguy** [comment]
Guess I should read all of the clsoed ones too.
