### ISSUE TITLE
Bad logic in the first few lines

### ISSUE THREAD

**Issue by blakev** [AndrewX192/lenovo-sa120-fanspeed-utility#9]
```python
if len(sys.argv) < 1:
    print("python fancontrol.py 1-7")
    sys.exit(-1)

fan = int(sys.argv[1])

if fan <= 0 or fan > 6:
    raise Exception("Fan speed must be between 1 and 7")
```

1. `len(sys.argv) < 1` will never happen because `sys.argv[0]` is always the name of the file

2. `if fan <= 0 or fan > 6` to get 1-7?? `if fan < 1 or fan > 7` -- as-is picking `7` breaks script

```python
            print("Enclosure found on " + device);
```

3. there are no semi-colon endings in python

**Comment by AndrewX192** [comment]
Looks like this was fixed in #11. I'm going to close this out
